export const moviesData = [
    {
      id: 1,
      name: "1917",
      description: "A World War I thriller about two British soldiers on a mission.",
      year: 2019,
      genre: "War, Drama",
      imageUrl: "/Assets/ninetine.jpg",
    },
    {
      id: 2,
      name: "Inception",
      description: "A skilled thief is given a chance at redemption if he can plant an idea in someone's mind.",
      year: 2010,
      genre: "Sci-Fi, Thriller",
      imageUrl: "/Assets/inception.png",
    },
    {
      id: 3,
      name: "Interstellar",
      description: "A team of explorers travels through a wormhole in space to ensure humanity's survival.",
      year: 2014,
      genre: "Sci-Fi, Adventure",
      imageUrl: "/Assets/interseller.png",
    },
    {
      id: 4,
      name: "The Dark Knight",
      description: "Batman faces his greatest challenge yet when the Joker unleashes chaos on Gotham.",
      year: 2008,
      genre: "Action, Crime",
      imageUrl: "/Assets/dark.png",
    },
    {
      id: 5,
      name: "Parasite",
      description: "A poor family schemes to become employed by a wealthy family and infiltrate their household.",
      year: 2019,
      genre: "Thriller, Drama",
      imageUrl: "/Assets/parasite.png",
    },
    {
      id: 6,
      name: "The Matrix",
      description: "A computer hacker learns about the true nature of reality and his role in the war against its controllers.",
      year: 1999,
      genre: "Sci-Fi, Action",
      imageUrl: "/Assets/matrix.png",
    },
    {
      id: 7,
      name: "Avengers: Endgame",
      description: "After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos' actions.",
      year: 2019,
      genre: "Action, Sci-Fi",
      imageUrl: "path/to/endgame-movie.jpg",
    },
    {
      id: 8,
      name: "Joker",
      description: "A mentally troubled stand-up comedian embarks on a downward spiral, leading to the creation of an iconic villain.",
      year: 2019,
      genre: "Drama, Crime",
      imageUrl: "path/to/joker-movie.jpg",
    },
    {
      id: 9,
      name: "Spider-Man: Into the Spider-Verse",
      description: "Teenager Miles Morales becomes Spider-Man and joins others from different dimensions to save the multiverse.",
      year: 2018,
      genre: "Animation, Action",
      imageUrl: "path/to/spiderverse-movie.jpg",
    },
  ];
  

  export const topCastData = [
    {
      id: 1,
      realName: "Leonardo DiCaprio",
      fakeName: "Dom Cobb",
      movieName: "Inception",
      imageUrl: "/Assets/leo.jpg",
    },
    {
      id: 2,
      realName: "Tom Hardy",
      fakeName: "Farrier",
      movieName: "Dunkirk",
      imageUrl: "/Assets/tom.jpg",
    },
    {
      id: 3,
      realName: "Matthew McConaughey",
      fakeName: "Cooper",
      movieName: "Interstellar",
      imageUrl: "/Assets/mathew.png",
    },
    {
      id: 4,
      realName: "Christian Bale",
      fakeName: "Bruce Wayne",
      movieName: "The Dark Knight",
      imageUrl: "/Assets/bale.jpg",
    },
    {
      id: 5,
      realName: "Brad Pitt",
      fakeName: "Cliff Booth",
      movieName: "Once Upon a Time in Hollywood",
      imageUrl: "/Assets/brad.jpg",
    },
    {
      id: 6,
      realName: "Joaquin Phoenix",
      fakeName: "Arthur Fleck",
      movieName: "Joker",
      imageUrl: "/Assets/jeo.jpg",
    },
    {
      id: 7,
      realName: "Scarlett Johansson",
      fakeName: "Natasha Romanoff",
      movieName: "Avengers: Endgame",
      imageUrl: "/Assets/SCARLET.jpg",
    },
  ];
  